<?PHP
require_once("./include/membersite_config.php");

if(!$fgmembersite->CheckLogin())
{
    $fgmembersite->RedirectToURL("login.php");
    exit;
}

?>
<?php
   //require_once("./staff_position.php");
   $wingg=$_REQUEST["r"];
   $query="select cd,dmn_dscrptn cadre,c1 tvm,c2 tcr,c3 ekm,c4 ktm,c5 kde,c6 total 
            from
            (select distinct 
            decode(ps_cdr_id,
                   'DA00','GR.A',
                   'DA01','GR.A',
                   'DA02','GR.A',
                   'DA03','GR.A',
                   'DA04','GR.A',
                   'DA05','GR.A',
                   'DA07','GR.A',
                   'DA08','GR.A',
                   'DA09','GR.A',
                   'DA10','GR.A',
                   'DB01','Sr AO/AO',
                   'DB02','Sr AO/AO',
                   'DB03','EDP',
                   'DB04','Sr AO/AO',
                   'DB05','Sr AO/AO',
                   'DB06','Sr AO/AO',
                   'DB07','PS/SrPS',
                   'DB08','EDP',
                   'DB09','Hindi Posts', 
                   'DB11','AAO/Supr',
                   'DB12','EDP',
                   'DB13','PS/SrPS',
                   'DB14','AAO/Supr',
                   'DB15','AAO/Supr',
                   'DB16','AAO/Supr',
                   'DB17','AAO/Supr',
                   'DB18','AAO/Supr',
                   'DB19','Adr/SrAdr',
                   'DB20','Hindi Posts',
                   'DB21','PS/SrPS',
                   'DB22','EDP',
                   'DB24','Sr AO/AO',
                   'DB25','Sr AO/AO',
                   'DB26','Sr AO/AO',
                   'DB27','Sr AO/AO',
                   'DB28','AAO/Supr',
                   'DB29','AAO/Supr',
                   'DB30','Sr AO/AO',
                   'DB31','Sr AO/AO',
                   'DB32','Sr AO/AO',
                   'DB33','Sr AO/AO',
                   'DB34','Sr AO/AO',
                   'DB35','Sr AO/AO',
                   'DB36','PS/SrPS',
                   'DB37','AAO/Supr',
                   'DC01','Adr/SrAdr',
                   'DC02','PS/SrPS',
                   'DC03','Hindi Posts',
                   'DC05','Adr/SrAdr',
                   'DC06','PS/SrPS',
                   'DC07','EDP',
                   'DC08','EDP',
                   'DC09','Adr/SrAdr',
                   'DC10','Clerk/MTS',
                   'DC11','Clerk/MTS',
                   'DC12','Clerk/MTS',
                   'DC13','PS/SrPS',
                   'DC14','EDP',
                   'DC15','Adr/SrAdr',
                   'DC16','Adr/SrAdr',
                   'DC17','EDP',
                   'DC18','Clerk/MTS',
                   'DC19','Hindi Posts',
                   'DD01','Clerk/MTS'
                   )
            cd from prsnl_infrmtn_systm
            where ps_cdr_id not in ('DB24','DB25','DB26','DB27','DB28','DB29','DB36',
                                     'DC06','DC08','DC14','DC15','DC16','DC19') 
            union select 'sum' cd from dual
            ) aa,

            (select 
            decode(ps_cdr_id,
                   'DA00','GR.A',
                   'DA01','GR.A',
                   'DA02','GR.A',
                   'DA03','GR.A',
                   'DA04','GR.A',
                   'DA05','GR.A',
                   'DA07','GR.A',
                   'DA08','GR.A',
                   'DA09','GR.A',
                   'DA10','GR.A',
                   'DB01','Sr AO/AO',
                   'DB02','Sr AO/AO',
                   'DB03','EDP',
                   'DB04','Sr AO/AO',
                   'DB05','Sr AO/AO',
                   'DB06','Sr AO/AO',
                   'DB07','PS/SrPS',
                   'DB08','EDP',
                   'DB09','Hindi Posts', 
                   'DB11','AAO/Supr',
                   'DB12','EDP',
                   'DB13','PS/SrPS',
                   'DB14','AAO/Supr',
                   'DB15','AAO/Supr',
                   'DB16','AAO/Supr',
                   'DB17','AAO/Supr',
                   'DB18','AAO/Supr',
                   'DB19','Adr/SrAdr',
                   'DB20','Hindi Posts',
                   'DB21','PS/SrPS',
                   'DB22','EDP',
                   'DB24','Sr AO/AO',
                   'DB25','Sr AO/AO',
                   'DB26','Sr AO/AO',
                   'DB27','Sr AO/AO',
                   'DB28','AAO/Supr',
                   'DB29','AAO/Supr',
                   'DB30','Sr AO/AO',
                   'DB31','Sr AO/AO',
                   'DB32','Sr AO/AO',
                   'DB33','Sr AO/AO',
                   'DB34','Sr AO/AO',
                   'DB35','Sr AO/AO',
                   'DB36','PS/SrPS',
                   'DB37','AAO/Supr',
                   'DC01','Adr/SrAdr',
                   'DC02','PS/SrPS',
                   'DC03','Hindi Posts',
                   'DC05','Adr/SrAdr',
                   'DC06','PS/SrPS',
                   'DC07','EDP',
                   'DC08','EDP',
                   'DC09','Adr/SrAdr',
                   'DC10','Clerk/MTS',
                   'DC11','Clerk/MTS',
                   'DC12','Clerk/MTS',
                   'DC13','PS/SrPS',
                   'DC14','EDP',
                   'DC15','Adr/SrAdr',
                   'DC16','Adr/SrAdr',
                   'DC17','EDP',
                   'DC18','Clerk/MTS',
                   'DC19','Hindi Posts',
                   'DD01','Clerk/MTS'
                   )
 
            cd1,count(ps_cdr_id) c1 from prsnl_infrmtn_systm where 
            ps_cdr_id not in ('DB24','DB25','DB26','DB27','DB28','DB29','DB36',
                                     'DC06','DC08','DC14','DC15','DC16','DC19') and
                    ps_room_no='TVM' and ps_wing='$wingg' AND   ps_flg='W'
                    group by 
                    decode(ps_cdr_id,
                   'DA00','GR.A',
                   'DA01','GR.A',
                   'DA02','GR.A',
                   'DA03','GR.A',
                   'DA04','GR.A',
                   'DA05','GR.A',
                   'DA07','GR.A',
                   'DA08','GR.A',
                   'DA09','GR.A',
                   'DA10','GR.A',
                   'DB01','Sr AO/AO',
                   'DB02','Sr AO/AO',
                   'DB03','EDP',
                   'DB04','Sr AO/AO',
                   'DB05','Sr AO/AO',
                   'DB06','Sr AO/AO',
                   'DB07','PS/SrPS',
                   'DB08','EDP',
                   'DB09','Hindi Posts', 
                   'DB11','AAO/Supr',
                   'DB12','EDP',
                   'DB13','PS/SrPS',
                   'DB14','AAO/Supr',
                   'DB15','AAO/Supr',
                   'DB16','AAO/Supr',
                   'DB17','AAO/Supr',
                   'DB18','AAO/Supr',
                   'DB19','Adr/SrAdr',
                   'DB20','Hindi Posts',
                   'DB21','PS/SrPS',
                   'DB22','EDP',
                   'DB24','Sr AO/AO',
                   'DB25','Sr AO/AO',
                   'DB26','Sr AO/AO',
                   'DB27','Sr AO/AO',
                   'DB28','AAO/Supr',
                   'DB29','AAO/Supr',
                   'DB30','Sr AO/AO',
                   'DB31','Sr AO/AO',
                   'DB32','Sr AO/AO',
                   'DB33','Sr AO/AO',
                   'DB34','Sr AO/AO',
                   'DB35','Sr AO/AO',
                   'DB36','PS/SrPS',
                   'DB37','AAO/Supr',
                   'DC01','Adr/SrAdr',
                   'DC02','PS/SrPS',
                   'DC03','Hindi Posts',
                   'DC05','Adr/SrAdr',
                   'DC06','PS/SrPS',
                   'DC07','EDP',
                   'DC08','EDP',
                   'DC09','Adr/SrAdr',
                   'DC10','Clerk/MTS',
                   'DC11','Clerk/MTS',
                   'DC12','Clerk/MTS',
                   'DC13','PS/SrPS',
                   'DC14','EDP',
                   'DC15','Adr/SrAdr',
                   'DC16','Adr/SrAdr',
                   'DC17','EDP',
                   'DC18','Clerk/MTS',
                   'DC19','Hindi Posts',
                   'DD01','Clerk/MTS'
                   )

                   union select 'sum' cd1,count(ps_idn) c1 from prsnl_infrmtn_systm 
                   where 
                   ps_cdr_id not in ('DB24','DB25','DB26','DB27','DB28','DB29','DB36',
                                     'DC06','DC08','DC14','DC15','DC16','DC19') and
                                     ps_room_no='TVM' and ps_wing='$wingg' AND   ps_flg='W'  
                                    
                    )a,

      (select 
      decode(ps_cdr_id,
                   'DA00','GR.A',
                   'DA01','GR.A',
                   'DA02','GR.A',
                   'DA03','GR.A',
                   'DA04','GR.A',
                   'DA05','GR.A',
                   'DA07','GR.A',
                   'DA08','GR.A',
                   'DA09','GR.A',
                   'DA10','GR.A',
                   'DB01','Sr AO/AO',
                   'DB02','Sr AO/AO',
                   'DB03','EDP',
                   'DB04','Sr AO/AO',
                   'DB05','Sr AO/AO',
                   'DB06','Sr AO/AO',
                   'DB07','PS/SrPS',
                   'DB08','EDP',
                   'DB09','Hindi Posts', 
                   'DB11','AAO/Supr',
                   'DB12','EDP',
                   'DB13','PS/SrPS',
                   'DB14','AAO/Supr',
                   'DB15','AAO/Supr',
                   'DB16','AAO/Supr',
                   'DB17','AAO/Supr',
                   'DB18','AAO/Supr',
                   'DB19','Adr/SrAdr',
                   'DB20','Hindi Posts',
                   'DB21','PS/SrPS',
                   'DB22','EDP',
                   'DB24','Sr AO/AO',
                   'DB25','Sr AO/AO',
                   'DB26','Sr AO/AO',
                   'DB27','Sr AO/AO',
                   'DB28','AAO/Supr',
                   'DB29','AAO/Supr',
                   'DB30','Sr AO/AO',
                   'DB31','Sr AO/AO',
                   'DB32','Sr AO/AO',
                   'DB33','Sr AO/AO',
                   'DB34','Sr AO/AO',
                   'DB35','Sr AO/AO',
                   'DB36','PS/SrPS',
                   'DB37','AAO/Supr',
                   'DC01','Adr/SrAdr',
                   'DC02','PS/SrPS',
                   'DC03','Hindi Posts',
                   'DC05','Adr/SrAdr',
                   'DC06','PS/SrPS',
                   'DC07','EDP',
                   'DC08','EDP',
                   'DC09','Adr/SrAdr',
                   'DC10','Clerk/MTS',
                   'DC11','Clerk/MTS',
                   'DC12','Clerk/MTS',
                   'DC13','PS/SrPS',
                   'DC14','EDP',
                   'DC15','Adr/SrAdr',
                   'DC16','Adr/SrAdr',
                   'DC17','EDP',
                   'DC18','Clerk/MTS',
                   'DC19','Hindi Posts',
                   'DD01','Clerk/MTS'
                   )

       cd2,count(ps_cdr_id) c2 
          from prsnl_infrmtn_systm where 
          ps_cdr_id not in ('DB24','DB25','DB26','DB27','DB28','DB29','DB36',
                                     'DC06','DC08','DC14','DC15','DC16','DC19') and
          ps_room_no='TCR' and ps_wing='$wingg' AND   ps_flg='W'
          group by 
          decode(ps_cdr_id,
                   'DA00','GR.A',
                   'DA01','GR.A',
                   'DA02','GR.A',
                   'DA03','GR.A',
                   'DA04','GR.A',
                   'DA05','GR.A',
                   'DA07','GR.A',
                   'DA08','GR.A',
                   'DA09','GR.A',
                   'DA10','GR.A',
                   'DB01','Sr AO/AO',
                   'DB02','Sr AO/AO',
                   'DB03','EDP',
                   'DB04','Sr AO/AO',
                   'DB05','Sr AO/AO',
                   'DB06','Sr AO/AO',
                   'DB07','PS/SrPS',
                   'DB08','EDP',
                   'DB09','Hindi Posts', 
                   'DB11','AAO/Supr',
                   'DB12','EDP',
                   'DB13','PS/SrPS',
                   'DB14','AAO/Supr',
                   'DB15','AAO/Supr',
                   'DB16','AAO/Supr',
                   'DB17','AAO/Supr',
                   'DB18','AAO/Supr',
                   'DB19','Adr/SrAdr',
                   'DB20','Hindi Posts',
                   'DB21','PS/SrPS',
                   'DB22','EDP',
                   'DB24','Sr AO/AO',
                   'DB25','Sr AO/AO',
                   'DB26','Sr AO/AO',
                   'DB27','Sr AO/AO',
                   'DB28','AAO/Supr',
                   'DB29','AAO/Supr',
                   'DB30','Sr AO/AO',
                   'DB31','Sr AO/AO',
                   'DB32','Sr AO/AO',
                   'DB33','Sr AO/AO',
                   'DB34','Sr AO/AO',
                   'DB35','Sr AO/AO',
                   'DB36','PS/SrPS',
                   'DB37','AAO/Supr',
                   'DC01','Adr/SrAdr',
                   'DC02','PS/SrPS',
                   'DC03','Hindi Posts',
                   'DC05','Adr/SrAdr',
                   'DC06','PS/SrPS',
                   'DC07','EDP',
                   'DC08','EDP',
                   'DC09','Adr/SrAdr',
                   'DC10','Clerk/MTS',
                   'DC11','Clerk/MTS',
                   'DC12','Clerk/MTS',
                   'DC13','PS/SrPS',
                   'DC14','EDP',
                   'DC15','Adr/SrAdr',
                   'DC16','Adr/SrAdr',
                   'DC17','EDP',
                   'DC18','Clerk/MTS',
                   'DC19','Hindi Posts',
                   'DD01','Clerk/MTS'
                   )

                   union select 'sum' cd2,count(ps_idn) c2 from prsnl_infrmtn_systm 
                   where
                   ps_cdr_id not in ('DB24','DB25','DB26','DB27','DB28','DB29','DB36',
                                     'DC06','DC08','DC14','DC15','DC16','DC19') and
                    ps_room_no='TCR' and ps_wing='$wingg' AND   ps_flg='W'
                   
          ) b,

      (select 
      decode(ps_cdr_id,
                   'DA00','GR.A',
                   'DA01','GR.A',
                   'DA02','GR.A',
                   'DA03','GR.A',
                   'DA04','GR.A',
                   'DA05','GR.A',
                   'DA07','GR.A',
                   'DA08','GR.A',
                   'DA09','GR.A',
                   'DA10','GR.A',
                   'DB01','Sr AO/AO',
                   'DB02','Sr AO/AO',
                   'DB03','EDP',
                   'DB04','Sr AO/AO',
                   'DB05','Sr AO/AO',
                   'DB06','Sr AO/AO',
                   'DB07','PS/SrPS',
                   'DB08','EDP',
                   'DB09','Hindi Posts', 
                   'DB11','AAO/Supr',
                   'DB12','EDP',
                   'DB13','PS/SrPS',
                   'DB14','AAO/Supr',
                   'DB15','AAO/Supr',
                   'DB16','AAO/Supr',
                   'DB17','AAO/Supr',
                   'DB18','AAO/Supr',
                   'DB19','Adr/SrAdr',
                   'DB20','Hindi Posts',
                   'DB21','PS/SrPS',
                   'DB22','EDP',
                   'DB24','Sr AO/AO',
                   'DB25','Sr AO/AO',
                   'DB26','Sr AO/AO',
                   'DB27','Sr AO/AO',
                   'DB28','AAO/Supr',
                   'DB29','AAO/Supr',
                   'DB30','Sr AO/AO',
                   'DB31','Sr AO/AO',
                   'DB32','Sr AO/AO',
                   'DB33','Sr AO/AO',
                   'DB34','Sr AO/AO',
                   'DB35','Sr AO/AO',
                   'DB36','PS/SrPS',
                   'DB37','AAO/Supr',
                   'DC01','Adr/SrAdr',
                   'DC02','PS/SrPS',
                   'DC03','Hindi Posts',
                   'DC05','Adr/SrAdr',
                   'DC06','PS/SrPS',
                   'DC07','EDP',
                   'DC08','EDP',
                   'DC09','Adr/SrAdr',
                   'DC10','Clerk/MTS',
                   'DC11','Clerk/MTS',
                   'DC12','Clerk/MTS',
                   'DC13','PS/SrPS',
                   'DC14','EDP',
                   'DC15','Adr/SrAdr',
                   'DC16','Adr/SrAdr',
                   'DC17','EDP',
                   'DC18','Clerk/MTS',
                   'DC19','Hindi Posts',
                   'DD01','Clerk/MTS'
                   )
       cd3,count(ps_cdr_id) c3 
          from prsnl_infrmtn_systm where 
          ps_cdr_id not in ('DB24','DB25','DB26','DB27','DB28','DB29','DB36',
                                     'DC06','DC08','DC14','DC15','DC16','DC19') and
          ps_room_no='EKM' and ps_wing='$wingg' AND   ps_flg='W'
          group by 
          decode(ps_cdr_id,
                   'DA00','GR.A',
                   'DA01','GR.A',
                   'DA02','GR.A',
                   'DA03','GR.A',
                   'DA04','GR.A',
                   'DA05','GR.A',
                   'DA07','GR.A',
                   'DA08','GR.A',
                   'DA09','GR.A',
                   'DA10','GR.A',
                   'DB01','Sr AO/AO',
                   'DB02','Sr AO/AO',
                   'DB03','EDP',
                   'DB04','Sr AO/AO',
                   'DB05','Sr AO/AO',
                   'DB06','Sr AO/AO',
                   'DB07','PS/SrPS',
                   'DB08','EDP',
                   'DB09','Hindi Posts', 
                   'DB11','AAO/Supr',
                   'DB12','EDP',
                   'DB13','PS/SrPS',
                   'DB14','AAO/Supr',
                   'DB15','AAO/Supr',
                   'DB16','AAO/Supr',
                   'DB17','AAO/Supr',
                   'DB18','AAO/Supr',
                   'DB19','Adr/SrAdr',
                   'DB20','Hindi Posts',
                   'DB21','PS/SrPS',
                   'DB22','EDP',
                   'DB24','Sr AO/AO',
                   'DB25','Sr AO/AO',
                   'DB26','Sr AO/AO',
                   'DB27','Sr AO/AO',
                   'DB28','AAO/Supr',
                   'DB29','AAO/Supr',
                   'DB30','Sr AO/AO',
                   'DB31','Sr AO/AO',
                   'DB32','Sr AO/AO',
                   'DB33','Sr AO/AO',
                   'DB34','Sr AO/AO',
                   'DB35','Sr AO/AO',
                   'DB36','PS/SrPS',
                   'DB37','AAO/Supr',
                   'DC01','Adr/SrAdr',
                   'DC02','PS/SrPS',
                   'DC03','Hindi Posts',
                   'DC05','Adr/SrAdr',
                   'DC06','PS/SrPS',
                   'DC07','EDP',
                   'DC08','EDP',
                   'DC09','Adr/SrAdr',
                   'DC10','Clerk/MTS',
                   'DC11','Clerk/MTS',
                   'DC12','Clerk/MTS',
                   'DC13','PS/SrPS',
                   'DC14','EDP',
                   'DC15','Adr/SrAdr',
                   'DC16','Adr/SrAdr',
                   'DC17','EDP',
                   'DC18','Clerk/MTS',
                   'DC19','Hindi Posts',
                   'DD01','Clerk/MTS'
                   )

                   union select 'sum' cd3,count(ps_idn) c3 from prsnl_infrmtn_systm 
                   where
                   ps_cdr_id not in ('DB24','DB25','DB26','DB27','DB28','DB29','DB36',
                                     'DC06','DC08','DC14','DC15','DC16','DC19') and
                   ps_room_no='EKM' and ps_wing='$wingg' AND   ps_flg='W'
                   
          ) c, 

      (select 
      decode(ps_cdr_id,
                   'DA00','GR.A',
                   'DA01','GR.A',
                   'DA02','GR.A',
                   'DA03','GR.A',
                   'DA04','GR.A',
                   'DA05','GR.A',
                   'DA07','GR.A',
                   'DA08','GR.A',
                   'DA09','GR.A',
                   'DA10','GR.A',
                   'DB01','Sr AO/AO',
                   'DB02','Sr AO/AO',
                   'DB03','EDP',
                   'DB04','Sr AO/AO',
                   'DB05','Sr AO/AO',
                   'DB06','Sr AO/AO',
                   'DB07','PS/SrPS',
                   'DB08','EDP',
                   'DB09','Hindi Posts', 
                   'DB11','AAO/Supr',
                   'DB12','EDP',
                   'DB13','PS/SrPS',
                   'DB14','AAO/Supr',
                   'DB15','AAO/Supr',
                   'DB16','AAO/Supr',
                   'DB17','AAO/Supr',
                   'DB18','AAO/Supr',
                   'DB19','Adr/SrAdr',
                   'DB20','Hindi Posts',
                   'DB21','PS/SrPS',
                   'DB22','EDP',
                   'DB24','Sr AO/AO',
                   'DB25','Sr AO/AO',
                   'DB26','Sr AO/AO',
                   'DB27','Sr AO/AO',
                   'DB28','AAO/Supr',
                   'DB29','AAO/Supr',
                   'DB30','Sr AO/AO',
                   'DB31','Sr AO/AO',
                   'DB32','Sr AO/AO',
                   'DB33','Sr AO/AO',
                   'DB34','Sr AO/AO',
                   'DB35','Sr AO/AO',
                   'DB36','PS/SrPS',
                   'DB37','AAO/Supr',
                   'DC01','Adr/SrAdr',
                   'DC02','PS/SrPS',
                   'DC03','Hindi Posts',
                   'DC05','Adr/SrAdr',
                   'DC06','PS/SrPS',
                   'DC07','EDP',
                   'DC08','EDP',
                   'DC09','Adr/SrAdr',
                   'DC10','Clerk/MTS',
                   'DC11','Clerk/MTS',
                   'DC12','Clerk/MTS',
                   'DC13','PS/SrPS',
                   'DC14','EDP',
                   'DC15','Adr/SrAdr',
                   'DC16','Adr/SrAdr',
                   'DC17','EDP',
                   'DC18','Clerk/MTS',
                   'DC19','Hindi Posts',
                   'DD01','Clerk/MTS'
                   )

       cd4,count(ps_cdr_id)  c4
          from prsnl_infrmtn_systm where
          ps_cdr_id not in ('DB24','DB25','DB26','DB27','DB28','DB29','DB36',
                                     'DC06','DC08','DC14','DC15','DC16','DC19') and 
          ps_room_no='KTM' and ps_wing='$wingg' AND   ps_flg='W'
          group by 
          decode(ps_cdr_id,
                   'DA00','GR.A',
                   'DA01','GR.A',
                   'DA02','GR.A',
                   'DA03','GR.A',
                   'DA04','GR.A',
                   'DA05','GR.A',
                   'DA07','GR.A',
                   'DA08','GR.A',
                   'DA09','GR.A',
                   'DA10','GR.A',
                   'DB01','Sr AO/AO',
                   'DB02','Sr AO/AO',
                   'DB03','EDP',
                   'DB04','Sr AO/AO',
                   'DB05','Sr AO/AO',
                   'DB06','Sr AO/AO',
                   'DB07','PS/SrPS',
                   'DB08','EDP',
                   'DB09','Hindi Posts', 
                   'DB11','AAO/Supr',
                   'DB12','EDP',
                   'DB13','PS/SrPS',
                   'DB14','AAO/Supr',
                   'DB15','AAO/Supr',
                   'DB16','AAO/Supr',
                   'DB17','AAO/Supr',
                   'DB18','AAO/Supr',
                   'DB19','Adr/SrAdr',
                   'DB20','Hindi Posts',
                   'DB21','PS/SrPS',
                   'DB22','EDP',
                   'DB24','Sr AO/AO',
                   'DB25','Sr AO/AO',
                   'DB26','Sr AO/AO',
                   'DB27','Sr AO/AO',
                   'DB28','AAO/Supr',
                   'DB29','AAO/Supr',
                   'DB30','Sr AO/AO',
                   'DB31','Sr AO/AO',
                   'DB32','Sr AO/AO',
                   'DB33','Sr AO/AO',
                   'DB34','Sr AO/AO',
                   'DB35','Sr AO/AO',
                   'DB36','PS/SrPS',
                   'DB37','AAO/Supr',
                   'DC01','Adr/SrAdr',
                   'DC02','PS/SrPS',
                   'DC03','Hindi Posts',
                   'DC05','Adr/SrAdr',
                   'DC06','PS/SrPS',
                   'DC07','EDP',
                   'DC08','EDP',
                   'DC09','Adr/SrAdr',
                   'DC10','Clerk/MTS',
                   'DC11','Clerk/MTS',
                   'DC12','Clerk/MTS',
                   'DC13','PS/SrPS',
                   'DC14','EDP',
                   'DC15','Adr/SrAdr',
                   'DC16','Adr/SrAdr',
                   'DC17','EDP',
                   'DC18','Clerk/MTS',
                   'DC19','Hindi Posts',
                   'DD01','Clerk/MTS'
                   )

                   union select 'sum' cd4,count(ps_idn) c4 from prsnl_infrmtn_systm 
                   where
                   ps_cdr_id not in ('DB24','DB25','DB26','DB27','DB28','DB29','DB36',
                                     'DC06','DC08','DC14','DC15','DC16','DC19') and
                    ps_room_no='KTM' and ps_wing='$wingg' AND   ps_flg='W'
                   
          ) d,
      (select 
      decode(ps_cdr_id,
                   'DA00','GR.A',
                   'DA01','GR.A',
                   'DA02','GR.A',
                   'DA03','GR.A',
                   'DA04','GR.A',
                   'DA05','GR.A',
                   'DA07','GR.A',
                   'DA08','GR.A',
                   'DA09','GR.A',
                   'DA10','GR.A',
                   'DB01','Sr AO/AO',
                   'DB02','Sr AO/AO',
                   'DB03','EDP',
                   'DB04','Sr AO/AO',
                   'DB05','Sr AO/AO',
                   'DB06','Sr AO/AO',
                   'DB07','PS/SrPS',
                   'DB08','EDP',
                   'DB09','Hindi Posts', 
                   'DB11','AAO/Supr',
                   'DB12','EDP',
                   'DB13','PS/SrPS',
                   'DB14','AAO/Supr',
                   'DB15','AAO/Supr',
                   'DB16','AAO/Supr',
                   'DB17','AAO/Supr',
                   'DB18','AAO/Supr',
                   'DB19','Adr/SrAdr',
                   'DB20','Hindi Posts',
                   'DB21','PS/SrPS',
                   'DB22','EDP',
                   'DB24','Sr AO/AO',
                   'DB25','Sr AO/AO',
                   'DB26','Sr AO/AO',
                   'DB27','Sr AO/AO',
                   'DB28','AAO/Supr',
                   'DB29','AAO/Supr',
                   'DB30','Sr AO/AO',
                   'DB31','Sr AO/AO',
                   'DB32','Sr AO/AO',
                   'DB33','Sr AO/AO',
                   'DB34','Sr AO/AO',
                   'DB35','Sr AO/AO',
                   'DB36','PS/SrPS',
                   'DB37','AAO/Supr',
                   'DC01','Adr/SrAdr',
                   'DC02','PS/SrPS',
                   'DC03','Hindi Posts',
                   'DC05','Adr/SrAdr',
                   'DC06','PS/SrPS',
                   'DC07','EDP',
                   'DC08','EDP',
                   'DC09','Adr/SrAdr',
                   'DC10','Clerk/MTS',
                   'DC11','Clerk/MTS',
                   'DC12','Clerk/MTS',
                   'DC13','PS/SrPS',
                   'DC14','EDP',
                   'DC15','Adr/SrAdr',
                   'DC16','Adr/SrAdr',
                   'DC17','EDP',
                   'DC18','Clerk/MTS',
                   'DC19','Hindi Posts',
                   'DD01','Clerk/MTS'
                   )

       cd5,count(ps_cdr_id) c5 
          from prsnl_infrmtn_systm where
          ps_cdr_id not in ('DB24','DB25','DB26','DB27','DB28','DB29','DB36',
                                     'DC06','DC08','DC14','DC15','DC16','DC19') and
                    ps_room_no='KDE' and ps_wing='$wingg' AND   ps_flg='W'
          group by 
          decode(ps_cdr_id,
                   'DA00','GR.A',
                   'DA01','GR.A',
                   'DA02','GR.A',
                   'DA03','GR.A',
                   'DA04','GR.A',
                   'DA05','GR.A',
                   'DA07','GR.A',
                   'DA08','GR.A',
                   'DA09','GR.A',
                   'DA10','GR.A',
                   'DB01','Sr AO/AO',
                   'DB02','Sr AO/AO',
                   'DB03','EDP',
                   'DB04','Sr AO/AO',
                   'DB05','Sr AO/AO',
                   'DB06','Sr AO/AO',
                   'DB07','PS/SrPS',
                   'DB08','EDP',
                   'DB09','Hindi Posts', 
                   'DB11','AAO/Supr',
                   'DB12','EDP',
                   'DB13','PS/SrPS',
                   'DB14','AAO/Supr',
                   'DB15','AAO/Supr',
                   'DB16','AAO/Supr',
                   'DB17','AAO/Supr',
                   'DB18','AAO/Supr',
                   'DB19','Adr/SrAdr',
                   'DB20','Hindi Posts',
                   'DB21','PS/SrPS',
                   'DB22','EDP',
                   'DB24','Sr AO/AO',
                   'DB25','Sr AO/AO',
                   'DB26','Sr AO/AO',
                   'DB27','Sr AO/AO',
                   'DB28','AAO/Supr',
                   'DB29','AAO/Supr',
                   'DB30','Sr AO/AO',
                   'DB31','Sr AO/AO',
                   'DB32','Sr AO/AO',
                   'DB33','Sr AO/AO',
                   'DB34','Sr AO/AO',
                   'DB35','Sr AO/AO',
                   'DB36','PS/SrPS',
                   'DB37','AAO/Supr',
                   'DC01','Adr/SrAdr',
                   'DC02','PS/SrPS',
                   'DC03','Hindi Posts',
                   'DC05','Adr/SrAdr',
                   'DC06','PS/SrPS',
                   'DC07','EDP',
                   'DC08','EDP',
                   'DC09','Adr/SrAdr',
                   'DC10','Clerk/MTS',
                   'DC11','Clerk/MTS',
                   'DC12','Clerk/MTS',
                   'DC13','PS/SrPS',
                   'DC14','EDP',
                   'DC15','Adr/SrAdr',
                   'DC16','Adr/SrAdr',
                   'DC17','EDP',
                   'DC18','Clerk/MTS',
                   'DC19','Hindi Posts',
                   'DD01','Clerk/MTS'
                   )

                   union select 'sum' cd5,count(ps_idn) c5 from prsnl_infrmtn_systm 
                   where
                   ps_cdr_id not in ('DB24','DB25','DB26','DB27','DB28','DB29','DB36',
                                     'DC06','DC08','DC14','DC15','DC16','DC19') and
                    ps_room_no='KDE' and ps_wing='$wingg' AND   ps_flg='W'
                   
          ) e,

      (select 
      decode(ps_cdr_id,
                   'DA00','GR.A',
                   'DA01','GR.A',
                   'DA02','GR.A',
                   'DA03','GR.A',
                   'DA04','GR.A',
                   'DA05','GR.A',
                   'DA07','GR.A',
                   'DA08','GR.A',
                   'DA09','GR.A',
                   'DA10','GR.A',
                   'DB01','Sr AO/AO',
                   'DB02','Sr AO/AO',
                   'DB03','EDP',
                   'DB04','Sr AO/AO',
                   'DB05','Sr AO/AO',
                   'DB06','Sr AO/AO',
                   'DB07','PS/SrPS',
                   'DB08','EDP',
                   'DB09','Hindi Posts', 
                   'DB11','AAO/Supr',
                   'DB12','EDP',
                   'DB13','PS/SrPS',
                   'DB14','AAO/Supr',
                   'DB15','AAO/Supr',
                   'DB16','AAO/Supr',
                   'DB17','AAO/Supr',
                   'DB18','AAO/Supr',
                   'DB19','Adr/SrAdr',
                   'DB20','Hindi Posts',
                   'DB21','PS/SrPS',
                   'DB22','EDP',
                   'DB24','Sr AO/AO',
                   'DB25','Sr AO/AO',
                   'DB26','Sr AO/AO',
                   'DB27','Sr AO/AO',
                   'DB28','AAO/Supr',
                   'DB29','AAO/Supr',
                   'DB30','Sr AO/AO',
                   'DB31','Sr AO/AO',
                   'DB32','Sr AO/AO',
                   'DB33','Sr AO/AO',
                   'DB34','Sr AO/AO',
                   'DB35','Sr AO/AO',
                   'DB36','PS/SrPS',
                   'DB37','AAO/Supr',
                   'DC01','Adr/SrAdr',
                   'DC02','PS/SrPS',
                   'DC03','Hindi Posts',
                   'DC05','Adr/SrAdr',
                   'DC06','PS/SrPS',
                   'DC07','EDP',
                   'DC08','EDP',
                   'DC09','Adr/SrAdr',
                   'DC10','Clerk/MTS',
                   'DC11','Clerk/MTS',
                   'DC12','Clerk/MTS',
                   'DC13','PS/SrPS',
                   'DC14','EDP',
                   'DC15','Adr/SrAdr',
                   'DC16','Adr/SrAdr',
                   'DC17','EDP',
                   'DC18','Clerk/MTS',
                   'DC19','Hindi Posts',
                   'DD01','Clerk/MTS'
                   )

       cd6,count(ps_cdr_id) c6 
          from prsnl_infrmtn_systm where
          ps_cdr_id not in ('DB24','DB25','DB26','DB27','DB28','DB29','DB36',
                                     'DC06','DC08','DC14','DC15','DC16','DC19') and 
          ps_wing='$wingg' AND   ps_flg='W'
          group by 
          decode(ps_cdr_id,
                   'DA00','GR.A',
                   'DA01','GR.A',
                   'DA02','GR.A',
                   'DA03','GR.A',
                   'DA04','GR.A',
                   'DA05','GR.A',
                   'DA07','GR.A',
                   'DA08','GR.A',
                   'DA09','GR.A',
                   'DA10','GR.A',
                   'DB01','Sr AO/AO',
                   'DB02','Sr AO/AO',
                   'DB03','EDP',
                   'DB04','Sr AO/AO',
                   'DB05','Sr AO/AO',
                   'DB06','Sr AO/AO',
                   'DB07','PS/SrPS',
                   'DB08','EDP',
                   'DB09','Hindi Posts', 
                   'DB11','AAO/Supr',
                   'DB12','EDP',
                   'DB13','PS/SrPS',
                   'DB14','AAO/Supr',
                   'DB15','AAO/Supr',
                   'DB16','AAO/Supr',
                   'DB17','AAO/Supr',
                   'DB18','AAO/Supr',
                   'DB19','Adr/SrAdr',
                   'DB20','Hindi Posts',
                   'DB21','PS/SrPS',
                   'DB22','EDP',
                   'DB24','Sr AO/AO',
                   'DB25','Sr AO/AO',
                   'DB26','Sr AO/AO',
                   'DB27','Sr AO/AO',
                   'DB28','AAO/Supr',
                   'DB29','AAO/Supr',
                   'DB30','Sr AO/AO',
                   'DB31','Sr AO/AO',
                   'DB32','Sr AO/AO',
                   'DB33','Sr AO/AO',
                   'DB34','Sr AO/AO',
                   'DB35','Sr AO/AO',
                   'DB36','PS/SrPS',
                   'DB37','AAO/Supr',
                   'DC01','Adr/SrAdr',
                   'DC02','PS/SrPS',
                   'DC03','Hindi Posts',
                   'DC05','Adr/SrAdr',
                   'DC06','PS/SrPS',
                   'DC07','EDP',
                   'DC08','EDP',
                   'DC09','Adr/SrAdr',
                   'DC10','Clerk/MTS',
                   'DC11','Clerk/MTS',
                   'DC12','Clerk/MTS',
                   'DC13','PS/SrPS',
                   'DC14','EDP',
                   'DC15','Adr/SrAdr',
                   'DC16','Adr/SrAdr',
                   'DC17','EDP',
                   'DC18','Clerk/MTS',
                   'DC19','Hindi Posts',
                   'DD01','Clerk/MTS'
                   )

                   union select 'sum' cd6,count(ps_idn) c6 from prsnl_infrmtn_systm 
                   where  
                   ps_cdr_id not in ('DB24','DB25','DB26','DB27','DB28','DB29','DB36',
                                     'DC06','DC08','DC14','DC15','DC16','DC19') and
                   ps_wing='$wingg' AND   ps_flg='W'
                   
          ) f,

      estt_dmn_mstr 

    where dmn_id(+)=cd and
              cd=cd1(+) and 
              cd=cd2(+) and 
              cd=cd3(+) and 
              cd=cd4(+) and
        cd=cd5(+) and
        cd=cd6(+)
         ";

	
	
	
	$order_by_param="nvl(".$_REQUEST["q"].",0)";
	$query.=" order by ".$order_by_param." ".$_SESSION['toggle'];
	if ($_SESSION['toggle']!='desc') $_SESSION['toggle']='desc';
	else $_SESSION['toggle']='';
	$respo="";
	
	//$conn=oci_connect("km","rt","localhost/test2");
	$conn=oci_connect($fgmembersite->orauser(),$fgmembersite->orap(),$fgmembersite->oraho());
	if (!$conn)
		{
	echo 'Failed to connect to Oracle';
	die("Connection failed: " . $conn->connect_error);
		}
	$statemen=oci_parse($conn,$query);
	oci_execute($statemen);
	while( $row=oci_fetch_array($statemen))
 	{
 $cadre=$row["CD"];
 $tvmcount=$row["TVM"];
 $tcrcount=$row["TCR"];
 $ekmcount=$row["EKM"];
 $ktycount=$row["KTM"];
 $kdecount=$row["KDE"];
 $sum=$row["TOTAL"];
 //echo 'the session variable is now:'.$_SESSION['toggle'];
 echo "<tr> 
       <td class='bl'>$cadre</td> 
       <td>$tvmcount</td>
       <td>$tcrcount</td> 
       <td>$ekmcount</td>
       <td>$ktycount</td>  
       <td>$kdecount</td>
       <td>$sum</td> 
        </tr>";
	}
	echo $respo;
	 
	 
			
?>